//
//  BreedList.swift
//  DogTracker
//
//  Created by Matthew Sousa on 3/8/21.
//  Copyright © 2021 Matthew Sousa. All rights reserved.
//

import Foundation


struct BreedList {
    
    // MARK: A -
    lazy var affenpinscher = Breed(name: "Affenpinscher")
    lazy var afganHound = Breed(name: "Afgan Hound")
    lazy var airedaleTerrier = Breed(name: "Airedale Terrier")
    lazy var akbash = Breed(name: "Akbash")
    lazy var akita = Breed(name: "Akita")
    lazy var alaskanKleeKai = Breed(name: "Alaskan Klee Kai")
    lazy var alaskanMalamute = Breed(name: "Alaskan Malamute")
    lazy var americanBullDog = Breed(name: "American Bulldog")
    lazy var americanCockerSpaniel = Breed(name: "American Cocker Spaniel")
    lazy var americanEskimoDog = Breed(name: "American Eskimo Dog")
    lazy var americanFoxhound = Breed(name: "American Foxhound")
    lazy var americanHairlessTerrier = Breed(name: "American Hairless Terrier")
    lazy var americanStaffordshireTerrier = Breed(name: "American Staffordshire Terrier")
    lazy var americanWaterSpaniel = Breed(name: "American Water Spaniel")
    lazy var anatolianShepherd = Breed(name: "Anatolian Shepherd")
    lazy var australianCattleDog = Breed(name: "Australian Cattle Dog")
    lazy var australianKelpie = Breed(name: "Australian Kelpie")
    lazy var australianShepherd = Breed(name: "Australian Shepherd")
    lazy var australianTerrier = Breed(name: "Australian Terrier")
    // MARK: B -
    lazy var basenji = Breed(name: "Basenji")
    lazy var bassetHound = Breed(name: "Basset Hound")
    lazy var beagle = Breed(name: "Beagle")
    lazy var beardedCollie = Breed(name: "Bearded Collie")
    lazy var beauceron = Breed(name: "Beauceron")
    lazy var bedlingtonTerrier = Breed(name: "Bedlington Terrier")
    lazy var belgianShepherdManlionis = Breed(name: "Belgian Shepherd / Manlinois")
    lazy var bedlingtonShepherdSheepdog = Breed(name: "Bedlington Shepherd / Sheepdog")
    lazy var belgianShepherdTervuren = Breed(name: "Belgian Shepherd / Tervuren")
    lazy var belgianShepherdDog = Breed(name: "Belgian Shepherd Dog")
    lazy var berneseMountainDog = Breed(name: "Bernese Mountain Dog")
    lazy var bichonFrise = Breed(name: "Bichon Frise")
    lazy var blackAndTanCoonhound = Breed(name: "Black & Tan Coonhound")
    lazy var blackRussianTerrier = Breed(name: "Black Russian Terrier")
    lazy var bloodhound = Breed(name: "Bloodhound")
    lazy var bluetickCoonhound = Breed(name: "Bluetick Coonhound")
    lazy var boerboel = Breed(name: "Boerboel")
    lazy var borderCollie = Breed(name: "Border Collie")
    lazy var borderTerrier = Breed(name: "Border Terrier")
    lazy var borzoi = Breed(name: "Borzoi")
    lazy var bostonTerrier = Breed(name: "Boston Terrier")
    lazy var bouvierDesFlandres = Breed(name: "Bouvier des Flandres")
    lazy var boxer = Breed(name: "Boxer")
    lazy var boykinSpaniel = Breed(name: "Boykin Spaniel")
    lazy var briard = Breed(name: "Briard")
    lazy var brittanySpaniel = Breed(name: "Brittany Spaniel")
    lazy var brusselsGriffon = Breed(name: "Brussels Griffon")
    lazy var bullTerrier = Breed(name: "Bull Terrier")
    lazy var bullmastiff = Breed(name: "Bullmastiff")
    // MARK: C -
    lazy var cairnTerrier = Breed(name: "Cairn Terrier")
    lazy var canaanDog = Breed(name: "Canaan Dog")
    lazy var caneCorso = Breed(name: "Cane Corso")
    lazy var cardiganWelshCorgi = Breed(name: "cardigan Welsh Corgi")
    lazy var carolinaDog = Breed(name: "Carolina Dog")
    lazy var caucasianShepherdDog = Breed(name: "Caucasian Shepherd Dog")
    lazy var cavalierKingCharlesSpaniel = Breed(name: "Cavalier King Charles Spaniel")
    lazy var chesapeakeBayRetriever = Breed(name: "Chesapeake Bay Retriever")
    lazy var chihuahua = Breed(name: "Chihuahua")
    lazy var chineseCrestedDog = Breed(name: "Chinese Crested Dog")
    lazy var chinook = Breed(name: "Chinook")
    lazy var chowChow = Breed(name: "Chow Chow")
    lazy var cirnecoDellEtna = Breed(name: "Cirneco dell'Etna")
    lazy var clumberSpaniel = Breed(name: "Clumber Spaniel")
    lazy var collie = Breed(name: "Collie")
    lazy var cotonDeTulear = Breed(name: "Coton de Tulear")
    lazy var curlyCoatedRetriever = Breed(name: "Curly Coated Retriever")
    // MARK: D-
    lazy var dachshund = Breed(name: "Dachshund")
    lazy var dalmation = Breed(name: "Dalmation")
    lazy var dandieDinmontTerrier = Breed(name: "Dandie Dinmont Terrier")
    lazy var dobermanPinscher = Breed(name: "Doberman Pinscher")
    lazy var dogoArgentino = Breed(name: "Dogo Argentino")
    lazy var dogueDeBordeaux = Breed(name: "Dogue de Bordeaux")
    lazy var dutchShepherd = Breed(name: "Dutch Shepherd")
    // MARK: E -
    lazy var englishBulldog = Breed(name: "English Bulldog")
    lazy var englishCockerSpaniel = Breed(name: "English Cocker Spaniel")
    lazy var englishCoonhound = Breed(name: "English Coonhound")
    lazy var englishFoxhound = Breed(name: "English Foxhound")
    lazy var englishPointer = Breed(name: "English Pointer")
    lazy var englishSetter = Breed(name: "English Setter")
    lazy var englishShepherd = Breed(name: "English Shepherd")
    lazy var englishSpringerSpaniel = Breed(name: "English Springer Spaniel")
    lazy var englishToySpaniel = Breed(name: "English Toy Spaniel")
    lazy var entlebucherMountainDog = Breed(name: "Entlebucher Mountain Dog")
    // MARK: F -
    lazy var fieldSpaniel = Breed(name: "Field Spaniel")
    lazy var finnishLapphund = Breed(name: "Finnish Lapphund")
    lazy var finnishSpitz = Breed(name: "Finnish Spitz")
    lazy var flatCoatedRetriever = Breed(name: "Flat Coated Retriever")
    lazy var frenchBulldog = Breed(name: "French Bulldog")
    // MARK: G -
    lazy var germanPinscher = Breed(name: "German Pinscher")
    lazy var germanShepherdDog = Breed(name: "German Shepherd Dog")
    lazy var germanShorthairedPointer = Breed(name: "German Shorthaired Pointer")
    lazy var germanSpitz = Breed(name: "German Spitz")
    lazy var germanWirehairedPointer = Breed(name: "German Wirehaired Pointer")
    lazy var giantSchnauzer = Breed(name: "Giant Schnauzer")
    lazy var glenOfImaalTerrier = Breed(name: "Glen of Imaal Terrier")
    lazy var goldenRetriever = Breed(name: "Golden Retriever")
    lazy var goldendoodle = Breed(name: "Goldendoodle")
    lazy var gordonSetter = Breed(name: "Gordon Setter")
    lazy var greatDane = Breed(name: "Great Dane")
    lazy var greatPyrenees = Breed(name: "Great Pyrenees")
    lazy var greaterSwissMountainDog = Breed(name: "Greater Swiss Mountain Dog")
    lazy var greyhound = Breed(name: "Greyhound")
    // MARK: H -
    lazy var hamiltonstovare = Breed(name: "Hamiltonstovare")
    lazy var harrier = Breed(name: "Harrier")
    lazy var havanese = Breed(name: "Havanese")
    lazy var hovawart = Breed(name: "Hovawart")
    // MARK: I -
    lazy var ibizanHound = Breed(name: "Ibizan Hound")
    lazy var icelandicSheepdog = Breed(name: "Icelandic Sheepdog")
    lazy var irishSetter = Breed(name: "Irish Setter")
    lazy var irishTerrier = Breed(name: "Irish Terrier")
    lazy var irishWaterSpaniel = Breed(name: "Irish Water Spaniel")
    lazy var irishWolfhound = Breed(name: "Irish Wolfhound")
    lazy var italianGreyhound = Breed(name: "Italian Greyhound")
    // MARK: J -
    lazy var jackRusselTerrier = Breed(name: "Jack Russel Terrier")
    lazy var japaneseChin = Breed(name: "Japanese Chin")
    lazy var jindo = Breed(name: "Jindo")
    // MARK: K -
    lazy var kaiKen = Breed(name: "Kai Ken")
    lazy var karelianBearDog = Breed(name: "Karelian Bear Dog")
    lazy var keeshond = Breed(name: "Keeshond")
    lazy var kerryBlueTerrier = Breed(name: "Kerry Blue Terrier")
    lazy var kishu = Breed(name: "Kishu")
    lazy var komondor = Breed(name: "Komondor")
    lazy var kuvasz = Breed(name: "Kuvasz")
    // MARK: L -
    lazy var labradorRetriever = Breed(name: "Labrador Retriever")
    lazy var lakelandTerrier = Breed(name: "Lakeland Terrier")
    lazy var lancashireHeeler = Breed(name: "Lancashire Heeler")
    lazy var largeMunsterlander = Breed(name: "Large Munsterlander")
    lazy var leonberger = Breed(name: "Leonberger")
    lazy var lhasaApso = Breed(name: "Lhasa Apso")
    lazy var louisianaCatahoulaLeopardDog = Breed(name: "Louisiana Catahoula Leopard Dog")
    lazy var lowchen = Breed(name: "Lowchen")
    lazy var lurcher = Breed(name: "Lurcher")
    // MARK: M -
    lazy var maltese = Breed(name: "Maltese")
    lazy var manchesterTerrier = Breed(name: "Manchester Terrier")
    lazy var maremmaSheepdog = Breed(name: "Maremma Sheepdog")
    lazy var mastiff = Breed(name: "Mastiff")
    lazy var miniatureBullTerrier = Breed(name: "Miniature Bull Terrier")
    lazy var miniatureDachshund = Breed(name: "Miniature Dachshund")
    lazy var miniaturePinscher = Breed(name: "Miniature Pinscher")
    lazy var miniaturePoodle = Breed(name: "Miniature Poodle")
    lazy var miniatureSchnauzer = Breed(name: "Miniature Schnauzer")
    lazy var mountainCur = Breed(name: "Mountain Cur")
    // MARK: N -
    lazy var neapolitanMastiff = Breed(name: "Neapolitan Mastiff")
    lazy var newfoundlandDog = Breed(name: "Newdoundland Dog")
    lazy var norfolkTerrier = Breed(name: "Norfolk Terrier")
    lazy var norwegianBuhund = Breed(name: "Norwegian Buhund")
    lazy var norwegianElkhound = Breed(name: "Norwegian Elkhound")
    lazy var norwegianLundehund = Breed(name: "Norwegian Lundehund")
    lazy var norwichTerrier = Breed(name: "Norwich Terrier")
    lazy var novaScotiaDuckTollingRetriever = Breed(name: "Nova Scotia Duck Tolling Retriever")
    // MARK: O -
    lazy var other = Breed(name: "Other")
    lazy var oldEnglishSheepdog = Breed(name: "Old English Sheepdog")
    lazy var otterhound = Breed(name: "Otterhound")
    // MARK: P -
    lazy var papillon = Breed(name: "Papillon")
    lazy var parsonRussellTerrier = Breed(name: "Parson Russell Terrier")
    lazy var patterdaleTerrier = Breed(name: "Patterdale Terrier")
    lazy var pekingese = Breed(name: "Pekingese")
    lazy var pembrokeWelshCorgi = Breed(name: "Pembroke Welsh Corgi")
    lazy var perroDePresaCanarioDog = Breed(name: "Perro de Presa Canario Dog")
    lazy var peruvianIncaOrchid = Breed(name: "Petit Basset Griddon Vendeen")
    lazy var pharaohHound = Breed(name: "Pharaoh Hound")
    lazy var plottHound = Breed(name: "Plott Hound")
    lazy var polishLowlandSheepdog = Breed(name: "Polish Lowland Sheepdog")
    lazy var pomeranian = Breed(name: "Pomeranian")
    lazy var poodle = Breed(name: "Poodle")
    lazy var portuguesePodengo = Breed(name: "Portuguese Podengo")
    lazy var portugueseWaterDog = Breed(name: "Portuguese Water Dog")
    lazy var pug = Breed(name: "Pug")
    lazy var puli = Breed(name: "Puli")
    lazy var pumi = Breed(name: "Pumi")
    lazy var pyreneanShepherd = Breed(name: "Pyrenean Shepherd")
    // MARK: R -
    lazy var ratTerrier = Breed(name: "Rat Terrier")
    lazy var redboneCoonhound = Breed(name: "Redbone Coonhound")
    lazy var rhodesianRidgeback = Breed(name: "Rhodesian Ridgeback")
    lazy var rottweiler = Breed(name: "Rottweiler")
    // MARK: S -
    lazy var saintBernard = Breed(name: "Saint Bernard")
    lazy var saluki = Breed(name: "Saluki")
    lazy var samoyed = Breed(name: "Samoyed")
    lazy var sarplaninac = Breed(name: "Sarplaninac")
    lazy var schipperke = Breed(name: "Schipperke")
    lazy var schnauzer = Breed(name: "Schnauzer")
    lazy var scottishDeerhound = Breed(name: "Scottish Deerhound")
    lazy var scottishTerrier = Breed(name: "Scottish Terrier")
    lazy var sealyhamTerrier = Breed(name: "Sealyham Terrier")
    lazy var sharPei = Breed(name: "Shar Pei")
    lazy var shetlandSheepdogSheltie = Breed(name: "Shetland Sheepdog / Sheltie")
    lazy var shibaInu = Breed(name: "Shiba Inu")
    lazy var shihTzu = Breed(name: "Shih Tzu")
    lazy var shollie = Breed(name: "Shollie")
    lazy var sibearianHusky = Breed(name: "Siberian Husky")
    lazy var silkyTerrier = Breed(name: "Silly Terrier")
    lazy var skyeTerrier = Breed(name: "Skye Terrier")
    lazy var sloughi = Breed(name: "Sloughi")
    lazy var smallMunsterlander = Breed(name: "Small Munsterlander")
    lazy var smoothFoxTerrier = Breed(name: "Smooth Fox Terrier")
    lazy var spanishWaterDog = Breed(name: "Spanish Water Dog")
    lazy var spinoneItaliano = Breed(name: "Spinone Italiano")
    lazy var staffordshireBullTerrier = Breed(name: "Staffordshire Bull Terrier")
    lazy var sussexSpaniel = Breed(name: "Sussex Spaniel")
    lazy var swedishVallhund = Breed(name: "Swedish Vallhund")
    // MARK: T -
    lazy var thaiRidgeback = Breed(name: "Thai Ridgeback")
    lazy var tibetanMastiff = Breed(name: "Tibetan Mastiff")
    lazy var tibetanSpaniel = Breed(name: "Tibetan Spaniel")
    lazy var tibetanTerrier = Breed(name: "Tibetan Terrier")
    lazy var tosa = Breed(name: "Tosa")
    lazy var toyFoxTerrier = Breed(name: "Toy Fox Terrier")
    lazy var toyManchesterTerrier = Breed(name: "Toy Manchester Terrier")
    lazy var treeingTennesseeBrindle = Breed(name: "Treeing Tennessee Brindle")
    lazy var treeingWalkerCoonhound = Breed(name: "Treeing Walker Coonhound")
    // MARK: V -
    lazy var vizsla = Breed(name: "Vizsla")
    // MARK: W -
    lazy var weimaraner = Breed(name: "Weimaraner")
    lazy var welshSpringerSpaniel = Breed(name: "Welsh Springer Spaniel")
    lazy var welshTerrier = Breed(name: "Welsh Terrier")
    lazy var westHighlandWhiteTerrierWestie = Breed(name: "West Highland White Terrier (Westie)")
    lazy var wheatenTerrier = Breed(name: "Wheaten Terrier")
    lazy var whippet = Breed(name: "Whippet")
    lazy var wireFoxTerrier = Breed(name: "Wire Fox Terrier")
    lazy var wirehairedPointingGriffon = Breed(name: "Wirehaired Pointing Griffon")
    // MARK: X -
    lazy var xoloitzcuintiliMexicanHairless = Breed(name: "Xoloitzcuintli (Mexican Hairless)")
    // MARK: Y -
    lazy var yorkshireTerrier = Breed(name: "Yorkshire Terrier")
    
    
    
        
    
    
    
}
